version: '3.7'

services:
  server:
    build: ./
    # for future process
    command: python app/main.py
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    shm_size: 4gb
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - PYTHONPATH=/app
    env_file:
      - ./config/development.all.env
      - ./config/secrets.env
    depends_on:
      - mongo_db
    links: 
      - mongo_db
    
  mongo_db:
    image: mongo
    restart: always
    hostname: mongo_db
    environment:
      MONGO_INITDB_DATABASE: prometeo_db
    ports:
        - "27019:27017"
