name: US

States:
- State: DC
  Ranges:
  - Range:
      begin: 20000
      end: 20098
  - Range:
      begin: 20200
      end: 20599
  - Range:
      begin: 56900
      end: 56972
- State: VA
  Ranges:
  - Range:
      begin: 20100
      end: 20199
  - Range:
      begin: 22009
      end: 24658
- State: MD
  Ranges:
  - Range:
      begin: 20600
      end: 21930
- State: WV
  Ranges:
  - Range:
      begin: 24700
      end: 26886
- State: NC
  Ranges:
  - Range:
      begin: 27006
      end: 28909
- State: SC
  Ranges:
  - Range:
      begin: 29000
      end: 29945
- State: GA
  Ranges:
  - Range:
      begin: 30002
      end: 31999
  - Range:
      begin: 39813
      end: 39901
- State: FL
  Ranges:
  - Range:
      begin: 32003
      end: 33994
  - Range:
      begin: 34100
      end: 34997
- State: AA
  Ranges:
  - Range:
      begin: 34000
      end: 34099
- State: AL
  Ranges:
  - Range:
      begin: 35004
      end: 36925
- State: TN
  Ranges:
  - Range:
      begin: 37010
      end: 38589
- State: MS
  Ranges:
  - Range:
      begin: 38600
      end: 39776
- State: KY
  Ranges:
  - Range:
      begin: 40003
      end: 42788
- State: OH
  Ranges:
  - Range:
      begin: 43000
      end: 45999
- State: IN
  Ranges:
  - Range:
      begin: 46000
      end: 47997
- State: MI
  Ranges:
  - Range:
      begin: 48000
      end: 49971
- State: IA
  Ranges:
  - Range:
      begin: 50000
      end: 52809
- State: WI
  Ranges:
  - Range:
      begin: 53000
      end: 54990
- State: MN
  Ranges:
  - Range:
      begin: 55000
      end: 56763
- State: SD
  Ranges:
  - Range:
      begin: 57000
      end: 57799
- State: ND
  Ranges:
  - Range:
      begin: 58000
      end: 58856
- State: MT
  Ranges:
  - Range:
      begin: 59000
      end: 59937
- State: IL
  Ranges:
  - Range:
      begin: 60000
      end: 62999
- State: MO
  Ranges:
  - Range:
      begin: 63000
      end: 65899
- State: KS
  Ranges:
  - Range:
      begin: 66002
      end: 67954
  - Range:
      begin: 68000
      end: 69367
- State: LA
  Ranges:
  - Range:
      begin: 70000
      end: 71497
- State: AR
  Ranges:
  - Range:
      begin: 71600
      end: 72959
- State: OK
  Ranges:
  - Range:
      begin: 73000
      end: 74966
- State: TX
  Ranges:
  - Range:
      begin: 75000
      end: 79999
  - Range:
      begin: 88510
      end: 88595
- State: CO
  Ranges:
  - Range:
      begin: 80000
      end: 81658
- State: WY
  Ranges:
  - Range:
      begin: 82000
      end: 83128
- State: ID
  Ranges:
  - Range:
      begin: 83200
      end: 83877
- State: UT
  Ranges:
  - Range:
      begin: 84000
      end: 84791
- State: AZ
  Ranges:
  - Range:
      begin: 85000
      end: 86556
- State: NM
  Ranges:
  - Range:
      begin: 87000
      end: 88439
- State: NV
  Ranges:
  - Range:
      begin: 88900
      end: 89883
- State: CA
  Ranges:
  - Range:
      begin: 90000
      end: 96162
- State: AP
  Ranges:
  - Range:
      begin: 96200
      end: 96698
- State: HI
  Ranges:
  - Range:
      begin: 96700
      end: 96898
- State: GU
  Ranges:
  - Range:
      begin: 96910
      end: 96932
- State: PW
  Ranges:
  - Range:
      begin: 96939
      end: 96940
- State: FM
  Ranges:
  - Range:
      begin: 96940
      end: 96944
- State: MP
  Ranges:
  - Range:
      begin: 96950
      end: 96952
- State: MH
  Ranges:
  - Range:
      begin: 96960
      end: 96970
- State: OR
  Ranges:
  - Range:
      begin: 97000
      end: 97920
- State: WA
  Ranges:
  - Range:
      begin: 98000
      end: 99403
- State: AK
  Ranges:
  - Range:
      begin: 99500
      end: 99950
- State: MA
  Ranges:
  - Range:
      begin: 1000
      end: 2791
- State: RI
  Ranges:
  - Range:
      begin: 2800
      end: 2940
- State: NH
  Ranges:
  - Range:
      begin: 3030
      end: 3897
- State: ME
  Ranges:
  - Range:
      begin: 3900
      end: 4992
- State: VT
  Ranges:
  - Range:
      begin: 5000
      end: 5907
- State: CT
  Ranges:
  - Range:
      begin: 6000
      end: 6928
- State: NJ
  Ranges:
  - Range:
      begin: 7000
      end: 8989
- State: AE
  Ranges:
  - Range:
      begin: 9000
      end: 9898
