name: US

States:
- State: DC
  Ranges:
  - Range:
      begin: 20001
      end: 20098
  - Range:
      begin: 20201
      end: 20599
  - Range:
      begin: 56901
      end: 56972
- State: VA
  Ranges:
  - Range:
      begin: 20101
      end: 20199
  - Range:
      begin: 22009
      end: 24658
- State: MD
  Ranges:
  - Range:
      begin: 20601
      end: 21930
- State: WV
  Ranges:
  - Range:
      begin: 24701
      end: 26886
- State: NC
  Ranges:
  - Range:
      begin: 27006
      end: 28909
- State: SC
  Ranges:
  - Range:
      begin: 29001
      end: 29945
- State: GA
  Ranges:
  - Range:
      begin: 30002
      end: 31999
  - Range:
      begin: 39813
      end: 39901
- State: FL
  Ranges:
  - Range:
      begin: 32003
      end: 33994
  - Range:
      begin: 34101
      end: 34997
- State: AA
  Ranges:
  - Range:
      begin: 34001
      end: 34099
- State: AL
  Ranges:
  - Range:
      begin: 35004
      end: 36925
- State: TN
  Ranges:
  - Range:
      begin: 37010
      end: 38589
- State: MS
  Ranges:
  - Range:
      begin: 38601
      end: 39776
- State: KY
  Ranges:
  - Range:
      begin: 40003
      end: 42788
- State: OH
  Ranges:
  - Range:
      begin: 43001
      end: 45999
- State: IN
  Ranges:
  - Range:
      begin: 46001
      end: 47997
- State: MI
  Ranges:
  - Range:
      begin: 48001
      end: 49971
- State: IA
  Ranges:
  - Range:
      begin: 50001
      end: 52809
- State: WI
  Ranges:
  - Range:
      begin: 53001
      end: 54990
- State: MN
  Ranges:
  - Range:
      begin: 55001
      end: 56763
- State: SD
  Ranges:
  - Range:
      begin: 57001
      end: 57799
- State: ND
  Ranges:
  - Range:
      begin: 58001
      end: 58856
- State: MT
  Ranges:
  - Range:
      begin: 59001
      end: 59937
- State: IL
  Ranges:
  - Range:
      begin: 60001
      end: 62999
- State: MO
  Ranges:
  - Range:
      begin: 63001
      end: 65899
- State: KS
  Ranges:
  - Range:
      begin: 66002
      end: 67954
  - Range:
      begin: 68001
      end: 69367
- State: LA
  Ranges:
  - Range:
      begin: 70001
      end: 71497
- State: AR
  Ranges:
  - Range:
      begin: 71601
      end: 72959
- State: OK
  Ranges:
  - Range:
      begin: 73001
      end: 74966
- State: TX
  Ranges:
  - Range:
      begin: 75001
      end: 79999
  - Range:
      begin: 88510
      end: 88595
- State: CO
  Ranges:
  - Range:
      begin: 80001
      end: 81658
- State: WY
  Ranges:
  - Range:
      begin: 82001
      end: 83128
- State: ID
  Ranges:
  - Range:
      begin: 83201
      end: 83877
- State: UT
  Ranges:
  - Range:
      begin: 84001
      end: 84791
- State: AZ
  Ranges:
  - Range:
      begin: 85001
      end: 86556
- State: NM
  Ranges:
  - Range:
      begin: 87001
      end: 88439
- State: NV
  Ranges:
  - Range:
      begin: 88901
      end: 89883
- State: CA
  Ranges:
  - Range:
      begin: 90001
      end: 96162
- State: AP
  Ranges:
  - Range:
      begin: 96201
      end: 96698
- State: HI
  Ranges:
  - Range:
      begin: 96701
      end: 96898
- State: GU
  Ranges:
  - Range:
      begin: 96910
      end: 96932
- State: PW
  Ranges:
  - Range:
      begin: 96939
      end: 96940
- State: FM
  Ranges:
  - Range:
      begin: 96941
      end: 96944
- State: MP
  Ranges:
  - Range:
      begin: 96950
      end: 96952
- State: MH
  Ranges:
  - Range:
      begin: 96960
      end: 96970
- State: OR
  Ranges:
  - Range:
      begin: 97001
      end: 97920
- State: WA
  Ranges:
  - Range:
      begin: 98001
      end: 99403
- State: AK
  Ranges:
  - Range:
      begin: 99501
      end: 99950
- State: MA
  Ranges:
  - Range:
      begin: 1001
      end: 2791
- State: RI
  Ranges:
  - Range:
      begin: 2801
      end: 2940
- State: NH
  Ranges:
  - Range:
      begin: 3031
      end: 3897
- State: ME
  Ranges:
  - Range:
      begin: 3901
      end: 4992
- State: VT
  Ranges:
  - Range:
      begin: 5001
      end: 5907
- State: CT
  Ranges:
  - Range:
      begin: 6001
      end: 6928
- State: NJ
  Ranges:
  - Range:
      begin: 7001
      end: 8989
- State: AE
  Ranges:
  - Range:
      begin: 9001
      end: 9898
