name: US

States:
- State: NY
  Range:  
    begin: 10001
    end: 14925
- State: PA
  Range:  
    begin: 15001
    end: 19640
- State: DE
  Range:  
    begin: 19701
    end: 19988
- State: DC
  Range:  
    begin: 20001
    end: 20098
- State: VA
  Range:  
    begin: 20101
    end: 20199
- State: DC
  Range:  
    begin: 20201
    end: 20599
- State: MD
  Range:  
    begin: 20601
    end: 21930
- State: VA
  Range:  
    begin: 22009
    end: 24658
- State: WV
  Range:  
    begin: 24701
    end: 26886
- State: NC
  Range:  
    begin: 27006
    end: 28909
- State: SC
  Range:  
    begin: 29001
    end: 29945
- State: GA
  Range:  
    begin: 30002
    end: 31999
- State: FL
  Range:  
    begin: 32003
    end: 33994
- State: AA
  Range:  
    begin: 34001
    end: 34099
- State: FL
  Range:  
    begin: 34101
    end: 34997
- State: AL
  Range:  
    begin: 35004
    end: 36925
- State: TN
  Range:  
    begin: 37010
    end: 38589
- State: MS
  Range:  
    begin: 38601
    end: 39776
- State: GA
  Range:  
    begin: 39813
    end: 39901
- State: KY
  Range:  
    begin: 40003
    end: 42788
- State: OH
  Range:  
    begin: 43001
    end: 45999
- State: IN
  Range:  
    begin: 46001
    end: 47997
- State: MI
  Range:  
    begin: 48001
    end: 49971
- State: IA
  Range:  
    begin: 50001
    end: 52809
- State: WI
  Range:  
    begin: 53001
    end: 54990
- State: MN
  Range:  
    begin: 55001
    end: 56763
- State: DC
  Range:  
    begin: 56901
    end: 56972
- State: SD
  Range:  
    begin: 57001
    end: 57799
- State: ND
  Range:  
    begin: 58001
    end: 58856
- State: MT
  Range:  
    begin: 59001
    end: 59937
- State: IL
  Range:  
    begin: 60001
    end: 62999
- State: MO
  Range:  
    begin: 63001
    end: 65899
- State: KS
  Range:  
    begin: 66002
    end: 67954
  Range:  
    begin: 68001
    end: 69367
- State: LA
  Range:  
    begin: 70001
    end: 71497
- State: AR
  Range:  
    begin: 71601
    end: 72959
- State: OK
  Range:  
    begin: 73001
    end: 74966
- State: TX
  Range:  
    begin: 75001
    end: 79999
- State: CO
  Range:  
    begin: 80001
    end: 81658
- State: WY
  Range:  
    begin: 82001
    end: 83128
- State: ID
  Range:  
    begin: 83201
    end: 83877
- State: UT
  Range:  
    begin: 84001
    end: 84791
- State: AZ
  Range:  
    begin: 85001
    end: 86556
- State: NM
  Range:  
    begin: 87001
    end: 88439
- State: TX
  Range:  
    begin: 88510
    end: 88595
- State: NV
  Range:  
    begin: 88901
    end: 89883
- State: CA
  Range:  
    begin: 90001
    end: 96162
- State: AP
  Range:  
    begin: 96201
    end: 96698
- State: HI
  Range:  
    begin: 96701
    end: 96898
- State: GU
  Range:  
    begin: 96910
    end: 96932
- State: PW
  Range:  
    begin: 96939
    end: 96940
- State: FM
  Range:  
    begin: 96941
    end: 96944
- State: MP
  Range:  
    begin: 96950
    end: 96952
- State: MH
  Range:  
    begin: 96960
    end: 96970
- State: OR
  Range:  
    begin: 97001
    end: 97920
- State: WA
  Range:  
    begin: 98001
    end: 99403
- State: AK
  Range:  
    begin: 99501
    end: 99950
- State: MA
  Range:  
    begin: 1001
    end: 2791
- State: RI
  Range:  
    begin: 2801
    end: 2940
- State: NH
  Range:  
    begin: 3031
    end: 3897
- State: ME
  Range:  
    begin: 3901
    end: 4992
- State: VT
  Range:  
    begin: 5001
    end: 5907
- State: CT
  Range:  
    begin: 6001
    end: 6928
- State: NJ
  Range:  
    begin: 7001
    end: 8989
- State: AE
  Range:  
    begin: 9001
    end: 9898
